alignment:
  adapter: CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
  adapter2: CTGTCTCTTATACACATCTGACGCTGCCGACGA
  aligner: bwa-mem
  chromosomes:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
  - '15'
  - '16'
  - '17'
  - '18'
  - '19'
  - '20'
  - '21'
  - '22'
  - X
  - Y
  docker:
    bwa: bwa:v0.0.2
    fastq_screen: fastq_screen:v0.0.2
    fastqc: fastqc:v0.0.2
    picard: picard:v0.0.3
    samtools: samtools:v0.0.3
    single_cell_pipeline: single_cell_pipeline:v0.6.16
    trimgalore: trimgalore:v0.0.2
  fastq_screen_params:
    aligner: bwa
    filter_contaminated_reads: false
    genomes:
    - name: grch37
      path: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.fa
    - name: mm10
      path: /juno/work/shah/reference/scp_testdata_ref/mouse/mm10_build38_mouse.fasta
    - name: salmon
      path: /juno/work/shah/reference/scp_testdata_ref/salmon/GCF_002021735.1_Okis_V1_genomic.fna
    strict_validation: true
  gc_windows: /juno/work/shah/reference/scp_testdata_ref/human/gc_windows.txt
  memory:
    med: 6
  picard_wgs_params:
    count_unpaired: false
    min_bqual: 20
    min_mqual: 20
  ref_genome: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.fa
aneufinder:
  chromosomes:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
  - '15'
  - '16'
  - '17'
  - '18'
  - '19'
  - '20'
  - '21'
  - '22'
  - X
  - Y
  docker:
    aneufinder: aneufinder:v0.0.1
    single_cell_pipeline: single_cell_pipeline:v0.6.16
  memory:
    med: 6
  ref_genome: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.fa
annotation:
  chromosomes:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
  - '15'
  - '16'
  - '17'
  - '18'
  - '19'
  - '20'
  - '21'
  - '22'
  - X
  - Y
  classifier_training_data: /juno/work/shah/reference/scp_testdata_ref/human/classifier_training_data.h5
  corrupt_tree_params:
    engine_nchains: 1
    engine_nscans: 10000
    lower_fraction: 0.05
    model_fnr_bound: 0.5
    model_fpr_bound: 0.1
    neighborhood_size: 2
  docker:
    cell_cycle_classifier: cell_cycle_classifier:v0.0.2
    corrupt_tree: corrupt_tree:v0.0.1
    single_cell_pipeline: single_cell_pipeline:v0.6.16
  fastqscreen_training_data: /juno/work/shah/reference/scp_testdata_ref/human/fastqscreen_training_data.csv
  good_cells:
  - - quality
    - ge
    - 0.75
  - - experimental_condition
    - notin
    - - NTC
      - NCC
      - gDNA
      - GM
  - - cell_call
    - in
    - - C1
  - - is_contaminated
    - in
    - - 'False'
      - 'false'
      - false
  map_cutoff: 0.9
  memory:
    med: 6
  num_states: 12
  ref_type: grch37
  reference_gc: /juno/work/shah/reference/scp_testdata_ref/human/reference_gc_grch37.csv
breakpoint_calling:
  destruct_config:
    genome_fai: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.fa.fai
    genome_fasta: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.fa
    gtf_filename: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.gtf
  docker:
    destruct: destruct:v0.0.5
    lumpy: lumpy:v0.0.3
    samtools: samtools:v0.0.3
    single_cell_pipeline: single_cell_pipeline:v0.6.16
  memory:
    high: 16
    low: 4
    med: 6
  ref_data_directory: /juno/work/shah/reference/scp_testdata_ref/human/
copy_number_calling:
  chromosomes:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
  - '15'
  - '16'
  - '17'
  - '18'
  - '19'
  - '20'
  - '21'
  - '22'
  - X
  - Y
  docker:
    single_cell_pipeline: remixt:v0.0.7
    titan: titan:v0.0.1
  extract_seqdata: {}
  max_cores: null
  memory:
    high: 16
    low: 4
    med: 6
  ref_data_dir: /juno/work/shah/reference/scp_testdata_ref/human/
  ref_genome: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.fa
  split_size: 10000000
  titan_params:
    chrom_info_filename: /juno/work/shah/reference/scp_testdata_ref/human/chromInfo.txt.gz
    gc_wig: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.gc.ws_1000.wig
    mappability_wig: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.gc.ws_1000.wig
    normal_contamination:
    - 0.2
    - 0.4
    - 0.6
    - 0.8
    num_clusters:
    - 1
    - 2
    ploidy:
    - 1
    - 2
    - 3
    - 4
    window_size: 1000
count_haps:
  chromosomes:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
  - '15'
  - '16'
  - '17'
  - '18'
  - '19'
  - '20'
  - '21'
  - '22'
  - X
  - Y
  docker:
    remixt: remixt:v0.0.7
    single_cell_pipeline: single_cell_pipeline:v0.6.16
  extract_seqdata:
    genome_fai_template: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.fa.fai
    genome_fasta_template: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.fa
  max_cores: null
  memory:
    high: 16
    low: 4
    med: 6
  ref_data_dir: /juno/work/shah/reference/scp_testdata_ref/human/
germline_calling:
  chromosomes:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
  - '15'
  - '16'
  - '17'
  - '18'
  - '19'
  - '20'
  - '21'
  - '22'
  - X
  - Y
  databases:
    mappability:
      local_path: /juno/work/shah/reference/scp_testdata_ref/human/wgEncodeCrgMapabilityAlign50mer.bigWig
      url: http://hgdownload-test.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeMapability/release3/wgEncodeCrgMapabilityAlign50mer.bigWig
    snpeff:
      data_dir: /juno/work/shah/reference/scp_testdata_ref/snpeff/data/
      db: GRCh37.75
  docker:
    samtools: samtools:v0.0.3
    single_cell_pipeline: single_cell_pipeline:v0.6.16
    snpeff: vcftools:v0.0.2
    vcftools: vcftools:v0.0.2
  max_cores: 8
  memory:
    high: 16
    low: 4
    med: 6
  ref_genome: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.fa
  split_size: 10000000
hmmcopy:
  bin_size: 50000
  chromosomes:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
  - '15'
  - '16'
  - '17'
  - '18'
  - '19'
  - '20'
  - '21'
  - '22'
  - X
  - Y
  docker:
    hmmcopy: hmmcopy:v0.0.5
    single_cell_pipeline: single_cell_pipeline:v0.6.16
  e: 0.999999
  eta: 50000
  exclude_list: /juno/work/shah/reference/scp_testdata_ref/human/repeats.satellite.regions
  g: 3
  gc_wig_file: /juno/work/shah/reference/hmmcopy/GRCh37-lite.gc.ws_50000.wig
  good_cells:
  - - median_hmmcopy_reads_per_bin
    - ge
    - 50
  - - is_contaminated
    - in
    - - 'False'
      - 'false'
      - false
  igv_segs_quality_threshold: 0.75
  kappa: 100,100,700,100,25,25,25,25,25,25,25,25
  lambda: 20
  m: 0,1,2,3,4,5,6,7,8,9,10,11
  map_cutoff: 0.9
  map_wig_file: /juno/work/shah/reference/hmmcopy/GRCh37-lite.map.ws_125_to_50000.wig
  memory:
    med: 6
  min_mqual: 20
  mu: 0,1,2,3,4,5,6,7,8,9,10,11
  multipliers:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  nu: 2.1
  num_states: 12
  ref_genome: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.fa
  s: 1
  smoothing_function: modal
  strength: 1000
infer_haps:
  chromosomes:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
  - '15'
  - '16'
  - '17'
  - '18'
  - '19'
  - '20'
  - '21'
  - '22'
  - X
  - Y
  docker:
    remixt: remixt:v0.0.7
    single_cell_pipeline: single_cell_pipeline:v0.6.16
  extract_seqdata:
    genome_fai_template: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.fa.fai
    genome_fasta_template: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.fa
  max_cores: null
  memory:
    high: 16
    low: 4
    med: 6
  ref_data_dir: /juno/work/shah/reference/scp_testdata_ref/human/
merge_bams:
  chromosomes:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
  - '15'
  - '16'
  - '17'
  - '18'
  - '19'
  - '20'
  - '21'
  - '22'
  - X
  - Y
  docker:
    samtools: samtools:v0.0.3
    single_cell_pipeline: single_cell_pipeline:v0.6.16
  max_cores: 8
  memory:
    high: 16
    low: 4
    med: 6
  one_split_job: true
  ref_genome: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.fa
  split_size: 10000000
refdir: /juno/work/shah/reference/scp_testdata_ref
split_bam:
  chromosomes:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
  - '15'
  - '16'
  - '17'
  - '18'
  - '19'
  - '20'
  - '21'
  - '22'
  - X
  - Y
  docker:
    samtools: samtools:v0.0.3
    single_cell_pipeline: single_cell_pipeline:v0.6.16
  max_cores: 8
  memory:
    high: 16
    low: 4
    med: 6
  one_split_job: true
  ref_genome: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.fa
  split_size: 10000000
sv_genotyping:
  docker:
    single_cell_pipeline: single_cell_pipeline:v0.6.16
    svtyper: svtyper:v0.0.1
  memory:
    high: 16
    low: 4
    med: 6
  ref_genome: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.fa
variant_calling:
  chromosomes:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
  - '15'
  - '16'
  - '17'
  - '18'
  - '19'
  - '20'
  - '21'
  - '22'
  - X
  - Y
  cosmic_status:
    kwargs:
      split_size: 10000000
  databases:
    cosmic:
      download_method: sftp
      host: sftp-cancer.sanger.ac.uk
      local_path: /juno/work/shah/reference/scp_testdata_ref/human/cosmic_v75.vcf.gz
      password: shahlabith
      remote_paths:
        coding: /files/grch37/cosmic/v75/VCF/CosmicCodingMuts.vcf.gz
        non_coding: /files/grch37/cosmic/v75/VCF/CosmicNonCodingVariants.vcf.gz
      user_name: awm3@sfu.ca
    dbsnp:
      local_path: /juno/work/shah/reference/scp_testdata_ref/human/dbsnp_b146_GRCh37p13.vcf.gz
      url: ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b146_GRCh37p13/VCF/common_all_20151104.vcf.gz
    mappability:
      local_path: /juno/work/shah/reference/scp_testdata_ref/human/wgEncodeCrgMapabilityAlign50mer.bigWig
      url: http://hgdownload-test.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeMapability/release3/wgEncodeCrgMapabilityAlign50mer.bigWig
    ref_genome:
      local_path: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.fa
      url: http://www.bcgsc.ca/downloads/genomes/9606/hg19/1000genomes/bwa_ind/genome/GRCh37-lite.fa
    snpeff:
      data_dir: /juno/work/shah/reference/scp_testdata_ref/snpeff/data/
      db: GRCh37.75
  dbsnp_status:
    kwargs:
      split_size: 10000000
  docker:
    mutationseq: mutationseq:v0.0.3
    single_cell_pipeline: single_cell_pipeline:v0.6.16
    strelka: strelka:v0.0.3
    vcftools: vcftools:v0.0.2
  mappability:
    kwargs:
      split_size: 10000000
  max_cores: 8
  memory:
    high: 16
    low: 4
    med: 6
  museq_params:
    baseq_threshold: 10
    buffer_size: 2G
    coverage: 4
    indl_threshold: 0.05
    mapq_threshold: 10
    normal_variant: 25
    purity: 70
    threshold: 0.5
    tumour_variant: 2
    verbose: true
  ref_genome: /juno/work/shah/reference/scp_testdata_ref/human/GRCh37-lite.fa
  snpeff:
    kwargs:
      split_size: 10000000
  split_size: 10000000
  tri_nucleotide_context:
    kwargs:
      split_size: 10000000
  use_depth_thresholds: true
